export enum JobStatus { DRAFT = 'DRAFT', OPEN = 'OPEN', PAUSED = 'PAUSED', CLOSED = 'CLOSED', ARCHIVED = 'ARCHIVED' }
export enum ResumeStatus { SUBMITTED = 'SUBMITTED', SCREENING = 'SCREENING', SHORTLISTED = 'SHORTLISTED', INTERVIEWING = 'INTERVIEWING', OFFERED = 'OFFERED', HIRED = 'HIRED', REJECTED = 'REJECTED' }
export enum InterviewResult { PASS = 'PASS', FAIL = 'FAIL', PENDING = 'PENDING' }
export enum OfferStatus { DRAFT = 'DRAFT', PENDING_APPROVAL = 'PENDING_APPROVAL', PENDING_SENIOR_APPROVAL = 'PENDING_SENIOR_APPROVAL', APPROVED = 'APPROVED', SENT = 'SENT', ACCEPTED = 'ACCEPTED', REJECTED = 'REJECTED', WITHDRAWN = 'WITHDRAWN' }
export enum InterviewType { PHONE = 'PHONE', ONSITE = 'ONSITE', VIDEO = 'VIDEO', TECHNICAL = 'TECHNICAL' }
export enum UserRole { HR = 'HR', INTERVIEWER = 'INTERVIEWER', HIRING_MANAGER = 'HIRING_MANAGER', ADMIN = 'ADMIN' }
export enum ApprovalLevel { LEVEL_1 = 'LEVEL_1', LEVEL_2 = 'LEVEL_2', LEVEL_3 = 'LEVEL_3' }
export enum ApprovalDecision { APPROVE = 'APPROVE', REJECT = 'REJECT', ESCALATE = 'ESCALATE' }
export const statusText: Record<string, string> = { DRAFT: '草稿', PENDING_APPROVAL: '待审批', PENDING_SENIOR_APPROVAL: '待高层审批', APPROVED: '已审批', SENT: '已发送', ACCEPTED: '已接受', REJECTED: '已拒绝', WITHDRAWN: '已撤回', OPEN: '开放', PAUSED: '暂停', CLOSED: '关闭', ARCHIVED: '归档', SUBMITTED: '已投递', SCREENING: '筛选中', SHORTLISTED: '候选池', INTERVIEWING: '面试中', OFFERED: 'Offer 阶段', HIRED: '已入职', PASS: '通过', FAIL: '未通过', PENDING: '待反馈' };
